#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -e

if [ -e /var/lib/anon-gw-anonymizer-config/first_install_extra_debs.skip ]; then
   return 0
fi
if [ -e /var/lib/anon-gw-anonymizer-config/first_install_extra_debs.done ]; then
   return 0
fi

## Prevents daemons from starting (the Tor daemon).
## Since this script gets started by systemd, another instance of systemd
## (started by the 'tor' package's Debian maintainer postinst script) would
## block forever.

delete=true
if [ -e /usr/sbin/policy-rc.d ]; then
   delete=false
fi

echo "exit 101" >> /usr/sbin/policy-rc.d
chmod +x /usr/sbin/policy-rc.d

/usr/lib/anon-gw-anonymizer-config/startup_helper &
pid="$!"
exit_code="0"
wait "$pid" || exit_code="$?"

if [ "$delete" = "true" ]; then
   ## Allow startup of daemons again.
   rm -f /usr/sbin/policy-rc.d
fi

mkdir --parents /var/lib/anon-gw-anonymizer-config
touch /var/lib/anon-gw-anonymizer-config/first_install_extra_debs.done

exit "$exit_code"
